name: TrueBlocksCore
services:
  core:
    image: trueblocks-core
    build: ./build/core
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - Index:/index
      - Cache:/cache

  monitors_watch:
    depends_on:
      - core
    restart: unless-stopped
    image: trueblocks-monitors-watch
    build: ./build/monitors-watch
    env_file: .env
    volumes:
      - Index:/index
      - Cache:/cache
      - exports:/exports
      - addresses:/addresses

volumes:
  Index:
  Cache:
  exports:
  addresses:
